SkillProfi/SkillProfi_WebSite/Controllers/ProjectDataController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SkillProfi_Shared;
using SkillProfi_WebSite.Interfaces;
using System;
using System.Threading.Tasks;
using SkillProfi_WebSite.Classes;

namespace SkillProfi_WebSite.Controllers
{
    [Authorize(Roles = "administrator")]
    public class ProjectDataController : Controller
    {
        private readonly ISkillProfi data;

        public ProjectDataController(ISkillProfi data)//(,ILogger<HomeController> logger,
        {
            //_logger = logger;
            this.data = data;
        }

        #region проекты
        /// <summary>
        /// get запрос редактировать проект
        /// </summary>
        /// <param name="id">идентификатор проекта</param>
        /// <returns></returns>
        [HttpGet]
        public async Task<IActionResult> EditProject(int? id)
        {
            try
            {
                Project cur_project = await data?.GetProjectByIdAsync(id);
                if (cur_project != null)
                {
                    await data.SetGeneralDataInViewDataDictionaryAsync(ViewData, User.IsInRole("administrator"));
                    ViewData["Path"] = $"{ViewData["MainPage"]} * {ViewData["ProjectPage"]} * Редактировать";//"Главная * Проекты * Редактировать";
                    return View("ProjectEditOrCreate", cur_project);
                }
                else
                    return NotFound();
            }
            catch (Exception ex)
            {
                return ExceptionView.View(ex, this);
            }
        }
        /// <summary>
        /// get запрос добавить проект
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public async Task<IActionResult> CreateProject()
        {
            try
            {
                await data.SetGeneralDataInViewDataDictionaryAsync(ViewData, User.IsInRole("administrator"));
                ViewData["Path"] = $"{ViewData["MainPage"]} * {ViewData["ProjectPage"]} * Добавить";//"Главная * Проекты * Добавить";
                Project cur_project = new();
                return View("ProjectEditOrCreate", cur_project);
            }
            catch (Exception ex)
            {
                return ExceptionView.View(ex, this);
            }
        }

        /// <summary>
        /// post запрос добавить/редактировать проект
        /// </summary>
        /// <param name="project">сзданный/отредактированный проект</param>
        /// <returns></returns>
        [HttpPost]
        public async Task<IActionResult> EditOrCreateProject(Project project)
        {
            try
            {
                if (ModelState.IsValid && await data?.EditOrCreateProjectAsync(project))
                {
                    return RedirectToAction("Projects");
                }
                else return NotFound();
            }
            catch (Exception ex)
            {
                return ExceptionView.View(ex, this);
            }
        }

        /// <summary>
        /// удалить проект
        /// </summary>
        /// <param name="id">идентификатор проекта</param>
        /// <returns></returns>
        [HttpPost]
        public async Task<IActionResult> RemoveProject(int? id)
        {
            try
            {
                if (ModelState.IsValid && await data?.RemoveProjectByIdAsync(id))
                {
                    return RedirectToAction("Projects");
                }
                else return NotFound();
            }
            catch (Exception ex)
            {
                return ExceptionView.View(ex, this);
            }
        }

        /// <summary>
        /// get  запрос отображение проектов
        /// </summary>
        /// <returns></returns>
        [AllowAnonymous]
        [HttpGet]
        public async Task<IActionResult> Projects()
        {
            try
            {
                await data.SetGeneralDataInViewDataDictionaryAsync(ViewData, User.IsInRole("administrator"));
                ViewData["Path"] = $"{ViewData["MainPage"]} * {ViewData["ProjectPage"]}"; //"Главная * Проекты";
                ViewData["Header"] = $"{ViewData["ProjectPageHeader"]}";//"Проекты";
                return View("Projects", await data?.GetProjectsAsync());
            }
            catch (Exception ex)
            {
                return ExceptionView.View(ex, this);
            }
        }

        /// <summary>
        /// get  запрос отображения проекта по Id 
        /// </summary>
        /// <param name="id">идентификатор проекта</param>
        /// <returns></returns>
        [AllowAnonymous]
        [HttpGet]
        public async Task<IActionResult> GetProject(int? id)
        {
            try
            {                
                Project cur_project = await data?.GetProjectByIdAsync(id);
                if (cur_project != null)
                {   
                    await data.SetGeneralDataInViewDataDictionaryAsync(ViewData, User.IsInRole("administrator"));
                    ViewData["Path"] = $"{ViewData["MainPage"]} * {ViewData["ProjectPage"]} * {cur_project.Header}"; //"Главная * Проекты * "
                    return View("Project", cur_project);
                }
                else
                    return NotFound();
            }
            catch (Exception ex)
            {
                return ExceptionView.View(ex, this);
            }
        }
        #endregion
    }
}

SkillProfi/SkillProfi_WebSite/Views/ProjectData/Project.cshtml
@using SkillProfi_Shared
@model Project
@{
    ViewData["Title"] = "Описание проекта " + Model.Header;
    if (User.Identity.IsAuthenticated && User.IsInRole("administrator"))
        Layout = "_Layout_Admin";
    else
        Layout = "_Layout_General";
}
<div class="container">
    <div class="card mb-3" style="border:hidden;">
        <div class="card-header-0" style="padding: 0.5rem 0rem;">
            <div class="row">
                <div class="col-10">
                    <h1 class="text-primary">@Model.Header</h1>
                </div>
                <div class="col-2">
                    <img class="card-img-top"
                         src="@(Model.Image?.Length > 0 ? $"data:image/jpeg;base64,{(Convert.ToBase64String(Model.Image))}":"" )"
                         alt="@Model.Header">
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-10" align="justify">
            @Html.Raw(Model.Description)
        </div>
    </div>
    <div class="col mb-3 mt-3" align="right" style="right:20%;">
        <a class="btn btn-primary btn-sm" href="~/ProjectData/Projects">< Назад</a>
    </div>
</div>

SkillProfi/SkillProfi_WebSite/Views/ProjectData/ProjectEditOrCreate.cshtml
@using SkillProfi_Shared
@model Project
@{
    if (User.Identity.IsAuthenticated && User.IsInRole("administrator"))
        Layout = "_Layout_Admin";
    else
        Layout = "_Layout_General";
    string header = Model.Id != 0 ? "Редактирование проекта" : "Добавление проекта";
    ViewData["Title"] = header;
}
<div class="container">
    <div class="row mb-3 mt-3">
        <h3 class="text-center">@header</h3>
    </div>
    <form method="post" asp-route-id="@Model.Id" asp-action="EditOrCreateProject" asp-controller="ProjectData" class="form" id="editform" enctype="multipart/form-data">
        <div class="row mb-3 mt-3">
            <div class="col-9">
                <p>Наименование проекта</p>
                <input class="form-control form-control-lg" asp-for="Header" id="HeaderProject" type="text"
                       value="@if (@Model.Id != 0) { @Model.Header} " />
            </div>

            <div class="col-3">
                <div class="col" align="center">
                    <img id="outputImage"
                         src="@( (Model.Id != 0 && Model.Image?.Length>0) ?  $"data:image/jpeg;base64,{(Convert.ToBase64String(Model.Image))}":"" )"
                         class="img-fluid"/>
                    <label class="btn btn-primary btn-lg mt=3">
                        <input type="file" asp-for="ImageFormFile" accept=".jpg,.jpeg,.png" onchange="loadFile(event)" style="display: none;">
                        <span>Выберите изображение</span>
                    </label>
                </div>
            </div>
            <div class="col-9">
                <p>Описание проекта</p>
                <textarea class="form-control form-control-lg" asp-for="Description" id="DescriptionProject" rows="3">@(Model.Id != 0 ? Model.Description :"")</textarea>
            </div>

        </div>
        <div class="row mb-3 mt-3">
            <div class="col" align="right">
                <button class="btn btn-primary btn-sm" id="saveButton" type="submit">
                    @(Model.Id != 0 ? "Сохранить" : "Добавить")
                </button>
            </div>
        </div>
    </form>
</div>
<script>
    //предпросмотр изображения
    var loadFile = function (event) {
        var outputImg = document.getElementById('outputImage');
        outputImg.src = URL.createObjectURL(event.target.files[0]);
        outputImg.onload = function () {
            //outputImg.style.width = '250px';
            //outputImg.style.height = 'auto';
            ActivateBtn();
            URL.revokeObjectURL(outputImg.src) // free memory
        }
    };
    //активность кнопки в зависимости от ввода информации
    var btn = document.getElementById("saveButton");
    var DescriptionElement = document.getElementById("DescriptionProject");
    var HeaderElement = document.getElementById("HeaderProject");
    btn.disabled = true;
    //подписываемся на событие изменения значения текста
    DescriptionElement.addEventListener("keyup", ActivateBtn, false);
    HeaderElement.addEventListener("keyup", ActivateBtn, false);
    function ActivateBtn() {
        activateButton([DescriptionElement.value, HeaderElement.value], btn);
    }
</script>

SkillProfi/SkillProfi_WebSite/Views/ProjectData/Projects.cshtml
@using SkillProfi_Shared
@model IEnumerable<Project>
@{
    ViewData["Title"] = "Список проектов";
    if (User.Identity.IsAuthenticated && User.IsInRole("administrator"))
        Layout = "_Layout_Admin";
    else
        Layout = "_Layout_General";
}

<div class=" container">
    <div class="row gx-4 gx-lg-5">
        @foreach (Project project in Model)
        {
            <!-- Карточки width="362" height="200"-->

            <div class="col-md-4 mb-5 mt-5">
                <div class="card h-70" style="border:hidden;">
                    <div class="card-body" style="padding: 0rem 0rem; border: 1px solid rgba(0, 0, 0, 0.125);" align="center">
                        <a href="~/ProjectData/GetProject/@project.Id">
                            <!--"card-img-top"-->
                            <img class="img-fluid" src="@(project.Image?.Length > 0 ? $"data:image/jpeg;base64,{(Convert.ToBase64String(project.Image))}":"" )"
                                 alt="@project.Header" />
                        </a>
                    </div>
                    <div class="card-header" style="border: 1px solid rgba(0, 0, 0, 0.125);">
                        <h5 class=" text-center">@project.Header</h5>
                    </div>
                    @if (User.Identity.IsAuthenticated && User.IsInRole("administrator"))
                    {
                        <div class="card-body" align="right">
                            <form asp-action="RemoveProject" asp-controller="ProjectData" asp-route-id="@project.Id" method="post" id="removeform_@project.Id">
                                <a href="~/ProjectData/EditProject/@project.Id"><img width="30" height="30" src="~/Images/edit.png" alt="Редактировать" /></a>
                                <a href="#" onclick="if (confirm('Вы действительно хотите удалить проект @project.Header?')) {document.getElementById('removeform_@project.Id').submit() }">
                                    <img width="30" height="30" src="~/images/delete.png" alt="Удалить" />
                                </a>
                            </form>
                        </div>
                    }
                </div>
            </div>
        }
    </div>
    @if (User.Identity.IsAuthenticated && User.IsInRole("administrator"))
    {
        <div class="col mb-3 mt-3" align="right" style="right:20%;">
            <a class="btn btn-primary btn-sm" href="~/ProjectData/CreateProject">Добавить проект</a>
        </div>
    }
</div>