SkillProfi/SkillProfi_WebSite/Controllers/ServiceDataController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SkillProfi_Shared;
using SkillProfi_WebSite.Interfaces;
using System;
using System.Threading.Tasks;
using SkillProfi_WebSite.Classes;

namespace SkillProfi_WebSite.Controllers
{
    [Authorize(Roles = "administrator")]
    public class ServiceDataController : Controller
    {
        private readonly ISkillProfi data;

        public ServiceDataController(ISkillProfi data)//(,ILogger<HomeController> logger,
        {
            //_logger = logger;
            this.data = data;
        }
        #region Услуги
        /// <summary>
        /// get  запрос отображение услуг
        /// </summary>
        /// <returns></returns>
        [AllowAnonymous]
        [HttpGet]
        public async Task<IActionResult> Services()
        {
            try
            {
                await data.SetGeneralDataInViewDataDictionaryAsync(ViewData, User.IsInRole("administrator"));
                ViewData["Path"] = $"{ViewData["MainPage"]} * {ViewData["ServicePage"]}";//"Главная * Услуги";
                ViewData["Header"] = $"{ViewData["ServicePageHeader"]}";
                return View(await data?.GetServiсesAsync());
            }
            catch (Exception ex)
            {
                return ExceptionView.View(ex, this);
            }
        }

        /// <summary>
        /// удалить услугу
        /// </summary>
        /// <param name="id">идентификатор услуги</param>
        /// <returns></returns>
        [HttpPost]
        public async Task<IActionResult> RemoveService(int? id)
        {
            try
            {
                if (ModelState.IsValid && await data?.RemoveServiceByIdAsync(id))
                {
                    return RedirectToAction("Services");
                }
                else return NotFound();
            }
            catch (Exception ex)
            {
                return ExceptionView.View(ex, this);
            }
        }

        /// <summary>
        /// post запрос добавить/редактировать услугу
        /// </summary>
        /// <param name="service">сзданная/отредактированная структура услуги</param>
        /// <returns></returns>
        [HttpPost]
        public async Task<IActionResult> EditOrCreateService(Service service)
        {
            try
            {
                if (ModelState.IsValid && await data?.EditOrCreateServiceAsync(service))
                {
                    return RedirectToAction("Services");
                }
                else return NotFound();
            }
            catch (Exception ex)
            {
                return ExceptionView.View(ex, this);
            }
        }

        /// <summary>
        /// get запрос редактировать услугу
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [HttpGet]
        public async Task<IActionResult> EditService(int? id)
        {
            try
            {

                Service cur_service = await data?.GetServiсeByIdAsync(id);
                if (cur_service != null)
                {
                    await data.SetGeneralDataInViewDataDictionaryAsync(ViewData, User.IsInRole("administrator"));
                    ViewData["Path"] = $"{ViewData["MainPage"]} * {ViewData["ServicePage"]} * Редактировать";//"Главная * Услуги * Редактировать";
                    return View("ServiceEditorCreate", cur_service);
                }
                else
                    return NotFound();
            }
            catch (Exception ex)
            {
                return ExceptionView.View(ex, this);
            }
        }
        /// <summary>
        /// get запрос создать услугу
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public async Task<IActionResult> CreateService()
        {
            try
            {
                await data.SetGeneralDataInViewDataDictionaryAsync(ViewData, User.IsInRole("administrator"));
                ViewData["Path"] = $"{ViewData["MainPage"]} * {ViewData["ServicePage"]} * Добавить";//"Главная * Услуги * Добавить";
                Service cur_service = new();
                return View("ServiceEditorCreate", cur_service);
            }
            catch (Exception ex)
            {
                return ExceptionView.View(ex, this);
            }
        }
        #endregion
    }
}

SkillProfi/SkillProfi_WebSite/Views/ServiceData/ServiceEditOrCreate.cshtml
@using SkillProfi_Shared
@model Service
@{
    if (User.Identity.IsAuthenticated && User.IsInRole("administrator"))
        Layout = "_Layout_Admin";
    else
        Layout = "_Layout_General";
    string header = Model.Id != 0 ? "Редактирование услуги" : "Добавление услуги";
    ViewData["Title"] = header;
}
<div class="container">
    <div class="row mb-3 mt-3">
        <h3 class="text-center">@header</h3>
    </div>
    <form method="post" asp-action="EditOrCreateService" asp-controller="ServiceData" asp-antiforgery="true" asp-route-id="@Model.Id" class="form" id="editform">
        <div class="row mb-3 mt-3">
            <div class="col">
                <p>Заголовок услуги</p>
                <input class="form-control form-control-lg" asp-for="Header" id="HeaderService" type="text"
                       value="@(Model.Id != 0 ? Model.Header:"")" />
            </div>
        </div>
        <div class="row mb-3 mt-3">
            <div class="col">
                <p>Описание Услуги</p>
                <textarea class="form-control form-control-lg" asp-for="Description" id="DescriptionService" rows="3">@(Model.Id != 0 ? Model.Description:"" )</textarea>
            </div>
        </div>
        <div class="col mb-3 mt-3" align="right">
            <button class="btn btn-primary" id="btnSubmint" type="submit">@(Model.Id != 0 ? "Сохранить" : "Добавить")</button>
        </div>
    </form>
</div>
<script src="js\myscript.js"></script>
<script>
    var btn = document.getElementById("btnSubmint");
    var DescriptionElement = document.getElementById("DescriptionService");
    var HeaderElement = document.getElementById("HeaderService");
    btn.disabled = true;
    //подписываемся на событие изменения значения текста
    DescriptionElement.addEventListener("keyup", ActivateBtn, false);
    HeaderElement.addEventListener("keyup", ActivateBtn, false);
    function ActivateBtn() {
        activateButton([DescriptionElement.value, HeaderElement.value], btn);
    }
</script>

SkillProfi/SkillProfi_WebSite/Views/ServiceData/Services.cshtml
@using SkillProfi_Shared
@model IEnumerable<Service>
@{
    ViewData["Title"] = "Список заявок";
    if (User.Identity.IsAuthenticated && User.IsInRole("administrator"))
        Layout = "_Layout_Admin";
    else
        Layout = "_Layout_General";
}
<div class="container">
    <!--раскрывающийся список-->
    <div class="accordion" id="accordionFlush">
        <!--data-bs-parent усли его удалить во всех item аккадиона будет возможность раскрыть все item без сворачивания раскрытых ранее-->
        @foreach (Service serviceItem in Model)
        {
            <!--item аккардиона-->
            <div class="accordion-item-0 mb-3 mt-3">
                <!--свернутая панель загаловок-->
                <!--flush-heading_1 - заменить на уникальное название на данной странице-->
                <h2 class="accordion-header" id="flush-heading_@serviceItem.Id">
                    <button class="accordion-button collapsed"
                            type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapse_@serviceItem.Id" aria-expanded="false" aria-controls="flush-collapse_@serviceItem.Id">
                        @serviceItem.Header
                    </button>
                </h2>
                <!--развернутая панель при нажатии на кнопку flush-heading_1-->
                <div id="flush-collapse_@serviceItem.Id" class="accordion-collapse collapse" aria-labelledby="flush-heading_@serviceItem.Id" data-bs-parent="#accordionFlush">
                    <div class="accordion-body">
                        @Html.Raw(@serviceItem.Description)
                    </div>
                </div>
            </div>
            @if (User.Identity.IsAuthenticated && User.IsInRole("administrator"))
            {
                <div class="row">
                    <form asp-action="RemoveService" asp-controller="ServiceData" asp-route-id="@serviceItem.Id" method="post" id="removeform_@serviceItem.Id">
                        <a href="~/ServiceData/EditService/@serviceItem.Id"><img width="30" height="30" src="~/Images/edit.png" alt="Редактировать" /></a>
                        <a href="#" onclick="if (confirm('Вы действительно хотите удалить услугу @serviceItem.Header?')) {document.getElementById('removeform_@serviceItem.Id').submit() }">
                            <img width="30" height="30" src="~/Images/delete.png" alt="Удалить" />
                        </a>
                    </form>
                </div>
            }
        }
    </div>
    @if (User.Identity.IsAuthenticated && User.IsInRole("administrator"))
    {
        <div class="col mb-3 mt-3" align="right" style="right:20%;">
            <a class="btn btn-primary btn-sm" href="~/ServiceData/CreateService">Добавить услугу</a>
        </div>
    }
</div>