SkillProfi/SkillProfi_WebSite/Controllers/EditInterfaceController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SkillProfi_Shared;
using SkillProfi_WebSite.Classes;
using SkillProfi_WebSite.Interfaces;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace SkillProfi_WebSite.Controllers
{
    [Authorize(Roles = "administrator")]
    public class EditInterfaceController : Controller
    {
        private readonly ISkillProfi data;
        public EditInterfaceController(ISkillProfi data)//(,ILogger<HomeController> logger,
        {
            //_logger = logger;
            this.data = data;
        }

        /// <summary>
        /// get запрос редакторования фраз блока заголовка страницы
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public async Task<IActionResult> EditHeaderDescription()
        {
            try
            {
                await data.SetGeneralDataInViewDataDictionaryAsync(ViewData, User.IsInRole("administrator"));
                return View("EditHeaderDescription", await data?.GetAllQuoteInTheHeaderAsync());
            }
            catch (Exception ex)
            {
                return ExceptionView.View(ex, this);
            }
        }
        /// <summary>
        /// post запрос сохранить фразы блока заголовка страницы
        /// </summary>
        /// <param name="headers">отредактированная запись фраз блока заголовка страницы</param>
        /// <returns></returns>
        [HttpPost]
        public async Task<IActionResult> SaveHeaderDescription(List<HeaderDescription> headers)
        {
            try
            {
                if (ModelState.IsValid && await data?.SetQuoteInTheHeaderAsync(headers))
                {
                    return RedirectToAction("Index", "BidData");
                }
                else return NotFound();
            }
            catch (Exception ex)
            {
                return ExceptionView.View(ex, this);
            }
        }
        /// <summary>
        /// get запрос редакторования названий главного меню и заголовков странницы
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public async Task<IActionResult> EditMenuNameAndPageHeader()
        {
            try
            {
                await data.SetGeneralDataInViewDataDictionaryAsync(ViewData, User.IsInRole("administrator"));
                return View("EditMenuNameAndPageHeader", await data?.GetMenuNameAndPageHeaderAsync());
            }
            catch (Exception ex)
            {
                return ExceptionView.View(ex, this);
            }
        }

        /// <summary>
        /// post запрос редакторования названий главного менюи заголовков странницы
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        public async Task<IActionResult> SaveMenuNameAndPageHeader(MenuNameAndPageHeader menu)
        {
            try
            {
                if (ModelState.IsValid && await data?.SetMenuNameAndPageHeaderAsync(menu))//
                {
                    return RedirectToAction("Index", "BidData");
                }
                else return NotFound();
            }
            catch (Exception ex)
            {
                return ExceptionView.View(ex, this);
            }
        }
    }
}

SkillProfi/SkillProfi_WebSite/Views/EditInterface/EditHeaderDescription.cshtml
@using SkillProfi_Shared
@model IEnumerable<HeaderDescription>
@{
    ViewData["Title"] = "Редактирование блока фраз заголовка";
    if (User.Identity.IsAuthenticated && User.IsInRole("administrator"))
        Layout = "_Layout_Admin";
    else
        Layout = "_Layout_General";
    int headerDescriptionCount = Model != null ? Model.Count() : 0;
    int i = 0;
}



<div class="container px-1 px-lg-1">
    <form id="editHeaderform" method="post" asp-action="SaveHeaderDescription" asp-controller="EditInterface" class="form">
        <h3 class="text-center mt-3">Добавить/редактировать цитаты блока заголовка меню</h3>
        <div id="form_parent">
            @if (Model != null)
            {
                foreach (HeaderDescription cur_header in Model)
                {
                    @*Блок для добаления ссылок  если меняем навание класса class="input-group mt-3" поменять его и в скрипте!!!!!!! *@
                    <div class="input-group mt-3">
                        <input type="hidden" name="headers[@i].Id" value="@cur_header.Id" id="hid_@i">
                        <input class="form-control ms-2 me-2" name="headers[@i].Description" type="text" placeholder="Фраза блока заголовка меню" value="@cur_header.Description" />
                        <a href="#" onclick="return deleteField(this)" class="btn btn-danger">X</a>
                    </div>
                    {
                        i++;
                    }

                }
            }

        </div>

        <div class="row mb-3">
            <div class="form-group mb-3 mt-3" align="center">
                <a class="btn btn-primary" onclick="return addField()" href="#">+ Добавить еще</a>
            </div>
        </div>

    </form>
    <div class="form-group mb-3 mt-3" align="right">
        <a class="btn btn-primary" onclick="ReplaseIdElements(); document.getElementById('editHeaderform').submit();" href="#">Сохранить</a>
    </div>
</div>
<script>
    //Добавление и удаление полей
    var curFieldNameId = @headerDescriptionCount; // Уникальное значение для атрибута name
    //изменение имен элементов формы
    function ReplaseElementName(elem, num) {
        if (elem) {
            var elemName = elem.name;
            if (elemName) {
                var setElemName = "";
                if (elemName.endsWith(".Id")) {
                    setElemName = "headers[" + num + "].Id";
                }
                else if (elemName.endsWith(".Description")) {
                    setElemName = "headers[" + num + "].Description";
                }
                if (setElemName) {
                    //console.log("Было_" + elem.name);
                    elem.setAttribute("name", setElemName);
                    //console.log("Стало_" + elem.name);
                }
            }
            if (elem.children) {
                for (var j = 0; j < elem.children.length; j++) {
                    ReplaseElementName(elem.children[j], num);
                }
            }
        }
    }
    //переиндексация элементов формы
    function ReplaseIdElements() {
        var divs = document.getElementsByClassName("input-group mt-3");
        if (divs) {
            for (var i = 0; i < divs.length; i++) {
                ReplaseElementName(divs[i], i);
            }
        }
    }

    //удаление поля фразы блока заголовка меню
    function deleteField(ele) {
        // Получаем доступ к ДИВу, содержащему поле
        var contDiv = ele.parentNode;
        contDiv.parentNode.removeChild(contDiv);
        //перенумерация элементов
        //ReplaseIdElements();
        // Возвращаем false, чтобы не было перехода по сслыке
        return false;
    }
    //добавление поля фразы блока заголовка меню
    function addField() {
        // Создаем элемент ДИВ
        var div = document.createElement("div");
        //задаем класс элемента DIV
        div.className = "input-group mt-3";
        // Добавляем HTML-контент с пом. свойства innerHTML
        var inner = "<input type=\"hidden\" name=\"headers[" + curFieldNameId + "].Id\" value=\"0\" id=\"hid__" + curFieldNameId + "\">" +
            "<input class=\"form-control ms-2 me-2\" name=\"headers[" + curFieldNameId + "].Description\" type=\"text\" placeholder=\"Фраза блока заголовка меню\"/>" +
            "<a onclick=\"return deleteField(this)\" href=\"#\" id=\"button_" + curFieldNameId + "\"class=\"btn btn-danger\">X</a>";
        //console.log(inner);
        div.innerHTML = inner;
        // Добавляем новый узел в конец списка полей
        document.getElementById("form_parent").appendChild(div);
        // Увеличиваем ID
        curFieldNameId++;
        //перенумерация элементов
        //ReplaseIdElements();
        // Возвращаем false, чтобы не было перехода по сслыке
        return false;
    }
</script>

SkillProfi/SkillProfi_WebSite/Views/EditInterface/EditMenuNameAndPageHeader.cshtml
@using SkillProfi_Shared
@model MenuNameAndPageHeader
@{
    ViewData["Title"] = "Изменение названий ссылок главного меню и заголовков страниц";
    if (User.Identity.IsAuthenticated && User.IsInRole("administrator"))
        Layout = "_Layout_Admin";
    else
        Layout = "_Layout_General";
}
<div class="container px-4 px-lg-5 mb-3">
    <form id="editMenuNameform" method="post" asp-action="SaveMenuNameAndPageHeader" asp-controller="EditInterface" class="form">
        <h3 class="text-center mt-3">Добавить/редактировать</h3>
        <input type="hidden" name="Id" value="@Model.Id">
        <div class="row">
            <div class="col text-center">
                <h5>Название меню</h5>
            </div>
            <div class="col text-center">
                <h5>Заголовок страницы</h5>
            </div>
        </div>
        <div class="row">
            <div class="col mb-3 mt-3">
                <input name="MainPage" id="PageMain" class="form-control" placeholder='Название меню "Главная страница"' type="text" value="@Model.MainPage" />
            </div>
            <div class="col mb-3 mt-3">
                <input name="MainPageHeader" id="PageMainHeader" class="form-control" placeholder='Заголовок страницы "Главная страница"' type="text" value="@Model.MainPageHeader" />
            </div>
        </div>

        <div class="row">
            <div class="col mb-3 mt-3">
                <input name="ProjectPage" id="PageProject" class="form-control" placeholder='Название меню "Проекты"' type="text" value="@Model.ProjectPage" />
            </div>
            <div class="col mb-3 mt-3">
                <input name="ProjectPageHeader" id="PageProjectHeader" class="form-control" placeholder='Заголовок страницы "Проекты"' type="text" value="@Model.ProjectPageHeader" />
            </div>
        </div>

        <div class="row">
            <div class="col mb-3 mt-3">
                <input name="ServicePage" id="PageService" class="form-control" placeholder='Название меню "Услуги"' type="text" value="@Model.ServicePage" />
            </div>
            <div class="col mb-3 mt-3">
                <input name="ServicePageHeader" id="PageServiceHeader" class="form-control" placeholder='Заголовок страницы "Услуги"' type="text" value="@Model.ServicePageHeader" />
            </div>
        </div>

        <div class="row">
            <div class="col mb-3 mt-3">
                <input name="BlogPage" id="PageBlog" class="form-control" placeholder='Название меню "Блог"' type="text" value="@Model.BlogPage" />
            </div>
            <div class="col mb-3 mt-3">
                <input name="BlogPageHeader" id="PageBlogHeader" class="form-control" placeholder='Заголовок страницы "Блог"' type="text" value="@Model.BlogPageHeader" />
            </div>
        </div>

        <div class="row">
            <div class="col mb-3 mt-3">
                <input name="ContactPage" id="PageContact" class="form-control" placeholder='Название меню "Контакты"' type="text" value="@Model.ContactPage" />
            </div>
            <div class="col mb-3 mt-3">
                <input name="ContactPageHeader" id="PageContactHeader" class="form-control" placeholder='Заголовок страницы "Контакты"' type="text" value="@Model.ContactPageHeader" />
            </div>
        </div>
        <div class="form-group mb-3 mt-3" align="right">
            <input id="btnSave" type="submit" class="btn btn-primary" value="Сохранить" />
        </div>
</form>
</div>
<script>
    var btn = document.getElementById("btnSave"); 
    var el1 = document.getElementById("PageMain");
    var el2 = document.getElementById("PageProject");
    var el3 = document.getElementById("PageService");
    var el4 = document.getElementById("PageBlog");
    var el5 = document.getElementById("PageContact");
    var elh1 = document.getElementById("PageMainHeader");
    var elh2 = document.getElementById("PageProjectHeader");
    var elh3 = document.getElementById("PageServiceHeader");
    var elh4 = document.getElementById("PageBlogHeader");
    var elh5 = document.getElementById("PageContactHeader");

    btn.disabled = true;
    //подписываемся на событие изменения значения текста
    el1.addEventListener("keyup", ActivateBtn, false);
    el2.addEventListener("keyup", ActivateBtn, false);
    el3.addEventListener("keyup", ActivateBtn, false);
    el4.addEventListener("keyup", ActivateBtn, false);
    el5.addEventListener("keyup", ActivateBtn, false);

    elh1.addEventListener("keyup", ActivateBtn, false);
    elh2.addEventListener("keyup", ActivateBtn, false);
    elh3.addEventListener("keyup", ActivateBtn, false);
    elh4.addEventListener("keyup", ActivateBtn, false);
    elh5.addEventListener("keyup", ActivateBtn, false);

    function ActivateBtn() {
        activateButton([el1.value, el2.value, el3.value, el4.value, el5.value], btn);
    }

</script>