SkillProfi/SkillProfi_WebSite/Controllers/BlogDataController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SkillProfi_Shared;
using SkillProfi_WebSite.Classes;
using SkillProfi_WebSite.Interfaces;
using System;
using System.Threading.Tasks;

namespace SkillProfi_WebSite.Controllers
{
    [Authorize(Roles = "administrator")]
    public class BlogDataController : Controller
    {
        private readonly ISkillProfi data;
        public BlogDataController(ISkillProfi data)//(,ILogger<HomeController> logger,
        {
            //_logger = logger;
            this.data = data;
        }

        #region Блог
        /// <summary>
        /// get запрос редактировать блог
        /// </summary>
        /// <param name="id">идентификатор блога</param>
        /// <returns></returns>
        [HttpGet]
        public async Task<IActionResult> EditBlog(int? id)
        {
            try
            {


                Blog cur_blog = await data?.GetBlogByIdAsync(id);
                if (cur_blog != null)
                {                
                    await data.SetGeneralDataInViewDataDictionaryAsync(ViewData, User.IsInRole("administrator"));
                    ViewData["Path"] = $"{ViewData["MainPage"]} * {ViewData["BlogPage"]} * Редактировать";//"Главная * Блог * Редактировать";
                    return View("BlogEditOrCreate", cur_blog);
                }
                else
                    return NotFound();
            }
            catch (Exception ex)
            {
                return ExceptionView.View(ex, this);
            }
        }
        /// <summary>
        /// get запрос добавить Блог
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public async Task<IActionResult> CreateBlog()
        {
            try
            {
                await data.SetGeneralDataInViewDataDictionaryAsync(ViewData, User.IsInRole("administrator"));
                ViewData["Path"] = $"{ViewData["MainPage"]} * {ViewData["BlogPage"]} * Добавить";//"Главная * Блог * Добавить";
                Blog cur_Blog = new();
                return View("BlogEditOrCreate", cur_Blog);
            }
            catch (Exception ex)
            {
                return ExceptionView.View(ex, this);
            }
        }

        /// <summary>
        /// post запрос добавить/редактировать блог
        /// </summary>
        /// <param name="blog">сзданный/отредактированный блог</param>
        /// <returns></returns>
        [HttpPost]
        public async Task<IActionResult> EditOrCreateBlog(Blog blog)
        {
            try
            {
                if (ModelState.IsValid && await data?.EditOrCreateBlogAsync(blog))
                {
                    return RedirectToAction("Blogs");
                }
                else return NotFound();
            }
            catch (Exception ex)
            {
                return ExceptionView.View(ex, this);
            }
        }

        /// <summary>
        /// удалить блог
        /// </summary>
        /// <param name="id">идентификатор блога</param>
        /// <returns></returns>
        [HttpPost]
        public async Task<IActionResult> RemoveBlog(int? id)
        {
            try
            {
                if (ModelState.IsValid && await data?.RemoveBlogByIdAsync(id))
                {
                    return RedirectToAction("Blogs");
                }
                else return NotFound();
            }
            catch (Exception ex)
            {
                return ExceptionView.View(ex, this);
            }
        }

        /// <summary>
        /// get  запрос отображение блогов
        /// </summary>
        /// <returns></returns>
        [AllowAnonymous]
        [HttpGet]
        public async Task<IActionResult> Blogs()
        {
            try
            {
                await data.SetGeneralDataInViewDataDictionaryAsync(ViewData, User.IsInRole("administrator"));
                ViewData["Path"] = $"{ViewData["MainPage"]} * {ViewData["BlogPage"]}";// "Главная * Блог";
                ViewData["Header"] = $"{ViewData["BlogPageHeader"]}";//"Блог";
                return View("Blogs", await data?.GetBlogsAsync());
            }
            catch (Exception ex)
            {
                return ExceptionView.View(ex, this);
            }
        }

        /// <summary>
        /// get  запрос отображения блога по Id 
        /// </summary>
        /// <param name="id">идентификатор блога</param>
        /// <returns></returns>
        [AllowAnonymous]
        [HttpGet]
        public async Task<IActionResult> GetBlog(int? id)
        {
            try
            {                
                Blog cur_blog = await data?.GetBlogByIdAsync(id);
                if (cur_blog != null)
                {
                    await data.SetGeneralDataInViewDataDictionaryAsync(ViewData, User.IsInRole("administrator"));
                    ViewData["Path"] = $"{ViewData["MainPage"]} * {ViewData["BlogPage"]} * {cur_blog.Header}";//"Главная * Блог * " + ;
                    return View("Blog", cur_blog);
                }
                else
                    return NotFound();
            }
            catch (Exception ex)
            {
                return ExceptionView.View(ex, this);
            }
        }
        #endregion
    }
}

SkillProfi/SkillProfi_WebSite/Views/BlogData/Blog.cshtml
@using SkillProfi_Shared
@model Blog
@{
    ViewData["Title"] = Model.Header;
    if (User.Identity.IsAuthenticated && User.IsInRole("administrator"))
        Layout = "_Layout_Admin";
    else
        Layout = "_Layout_General";
}
<div class="container">
    <div class="card mb-3" style="border:hidden;">
        <div class="card-header-0" style="padding: 0.5rem 0rem;">
            <div class="row">
                <h1 class="text-primary">@Model.Header</h1>
            </div>
        </div>
    </div>
    <div class="row text-secondary mb-3 mt-3">
        @Model.Date.ToString("dd MMMM yyyy")
    </div>
    <div class="row">
        <div class="col-2 mb-3">
            <img class="card-img-top"
                 src="@(Model.Image?.Length > 0 ? $"data:image/jpeg;base64,{(Convert.ToBase64String(Model.Image))}":"" )"
                 alt="@Model.Header">
        </div>
        <div class="col-10 mb-3" align="justify">
            @Html.Raw(Model.Description)
        </div>
    </div>
    <div class="col mb-3 mt-3" align="right" style="right:20%;">
        <a class="btn btn-primary btn-sm" href="~/BlogData/Blogs">< Назад</a>
    </div>
</div>

SkillProfi/SkillProfi_WebSite/Views/BlogData/BlogEditOrCreate.cshtml
@using SkillProfi_Shared
@model Blog
@{
    if (User.Identity.IsAuthenticated && User.IsInRole("administrator"))
        Layout = "_Layout_Admin";
    else
        Layout = "_Layout_General";
    string header = Model.Id != 0 ? "Редактирование блога" : "Добавление блога";
    ViewData["Title"] = header;
}
<div class="container">
    <div class="row mb-3 mt-3">
        <h3 class="text-center">@header</h3>
    </div>
    <form method="post" asp-route-id="@Model.Id" asp-action="EditOrCreateBlog" asp-controller="BlogData" class="form" id="editform" enctype="multipart/form-data">
        <div class="row mb-3 mt-3">
            <div class="row">
                <div class="col-9">
                    <div class="col">
                        <p>Название блога</p>
                        <input class="form-control form-control-lg" asp-for="Header" id="HeaderBlog" type="text"
                               value="@if (@Model.Id != 0) { @Model.Header} " />
                    </div>
                    <div class="col">
                        <p>Дата</p>
                        <input type="date" class="form-control form-control-lg" asp-for="Date" id="DateBlog" />
                    </div>
                </div>
                <div class="col-3">
                    <div class="col" align="center">
                        <img id="outputImage"
                             src="@( (Model.Id != 0 && Model.Image?.Length>0) ?  $"data:image/jpeg;base64,{(Convert.ToBase64String(Model.Image))}":"" )" 
                             class="img-fluid"/>
                        @* width = "@( (Model.Id != 0 && Model.Image?.Length>0) ? "250px":"auto" )" height = "auto"*@
                        <label class="btn btn-primary btn-lg mt=3">
                            <input type="file" asp-for="ImageFormFile" accept=".jpg,.jpeg,.png" onchange="loadFile(event)" style="display: none;">
                            <span>Выберите изображение</span>
                        </label>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-9">
                    <p>Описание блога</p>
                    <textarea class="form-control form-control-lg" asp-for="Description" id="DescriptionBlog" rows="3">@(Model.Id != 0 ? Model.Description :"")</textarea>
                </div>
            </div>


        </div>
        <div class="row mb-3 mt-3">
            <div class="col" align="right">
                <button class="btn btn-primary btn-sm" id="saveButton" type="submit">
                    @(Model.Id != 0 ? "Сохранить" : "Добавить")
                </button>
            </div>
        </div>
    </form>
</div>
<script>
    //предпросмотр изображения
    var loadFile = function (event) {
        var outputImg = document.getElementById('outputImage');
        outputImg.src = URL.createObjectURL(event.target.files[0]);
        outputImg.onload = function () {
            //outputImg.style.width = '250px';
            //outputImg.style.height = 'auto';
            ActivateBtn();
            URL.revokeObjectURL(outputImg.src) // free memory
        }
    };
    //активность кнопки в зависимости от ввода информации
    var btn = document.getElementById("saveButton");
    var DescriptionElement = document.getElementById("DescriptionBlog");
    var HeaderElement = document.getElementById("HeaderBlog");
    var dateElement = document.getElementById("DateBlog");
    btn.disabled = true;
    //подписываемся на событие изменения значения текста
    DescriptionElement.addEventListener("keyup", ActivateBtn, false);
    HeaderElement.addEventListener("keyup", ActivateBtn, false);
    dateElement.addEventListener("change", ActivateBtn, false);
    function ActivateBtn() {
        activateButton([DescriptionElement.value, HeaderElement.value, dateElement.value], btn);
    }
</script>

SkillProfi/SkillProfi_WebSite/Views/BlogData/Blogs.cshtml
@using SkillProfi_Shared
@model IEnumerable<Blog>
@{
    ViewData["Title"] = ViewData["Header"]!=null ? ViewData["Header"] : ViewData["BlogPage"];
    if (User.Identity.IsAuthenticated && User.IsInRole("administrator"))
        Layout = "_Layout_Admin";
    else
        Layout = "_Layout_General";
}

<div class="container">

    <div class="row gx-4 gx-lg-5">
        @foreach (Blog blog in Model)
        {
            <!-- Карточки width="362" height="200"-->
            <div class="col-md-3 mb-3 mt-3">
                <div class="card h-75 " style="border:hidden;">
                    <div class="card-body text-secondary">
                        @blog.Date.ToString("dd MMMM yyyy")
                    </div>
                    <div class="card-body" style="padding: 0rem 0rem; border: 1px solid rgba(0, 0, 0, 0.125);" align="center">
                        <a href="~/BlogData/GetBlog/@blog.Id">
                            <!--"card-img-top"-->
                            <img class="img-fluid"
                                 src="@(blog.Image?.Length > 0 ? $"data:image/jpeg;base64,{(Convert.ToBase64String(blog.Image))}":"" )"
                                 alt="@blog.Header" />
                        </a>
                    </div>
                    <div class="card-body text-center" style="border: 1px solid rgba(0, 0, 0, 0.125);">
                        <h5><b>@blog.Header</b></h5>
                    </div>
                    <div class="card-body" style="border: 1px solid rgba(0, 0, 0, 0.125);">
                        <p align="justify" style="display: -webkit-box;
									    -webkit-line-clamp: 5;
									    -webkit-box-orient: vertical;
									    overflow: hidden;">
                            @SkillProfiHelper.GetStringWithOutHtml(blog.Description)
                        </p>
                    </div>
                    @if (User.Identity.IsAuthenticated && User.IsInRole("administrator"))
                    {
                        <div class="card-body" align="right">
                            <form asp-action="RemoveBlog" asp-controller="BlogData" asp-route-id="@blog.Id" method="post" id="removeform_@blog.Id">
                                <a href="~/BlogData/EditBlog/@blog.Id"><img width="30" height="30" src="~/Images/edit.png" alt="Редактировать" /></a>
                                <a href="#" onclick="if (confirm('Вы действительно хотите удалить блог @blog.Header?')) {document.getElementById('removeform_@blog.Id').submit() }">
                                    <img width="30" height="30" src="~/images/delete.png" alt="Удалить" />
                                </a>
                            </form>
                        </div>
                    }
                </div>
            </div>
        }
    </div>
    @if (User.Identity.IsAuthenticated && User.IsInRole("administrator"))
    {
        <div class="col mb-3 mt-3" align="right" style="right:20%;">
            <a class="btn btn-primary btn-sm" href="~/BlogData/CreateBlog">Добавить блог</a>
        </div>
    }
</div>